"""add workout logging

Revision ID: 4b6ac06f4181
Revises: 758b7be914c9
Create Date: 2026-08-18 16:11:34.760197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b6ac06f4181'
down_revision = '758b7be914c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_plan_id', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('day_index >= 0', name='ck_session_day_index_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_key', sa.String(length=100), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.CheckConstraint('reps >= 0', name='ck_log_reps_nonnegative'),
    sa.CheckConstraint('set_number > 0', name='ck_log_set_number_positive'),
    sa.CheckConstraint('weight >= 0', name='ck_log_weight_nonnegative'),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_session_id', 'exercise_key', 'set_number', name='uq_log_session_exercise_set')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_log')
    op.drop_table('workout_session')
    # ### end Alembic commands ###
